name: Example GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3001272@ds.study.iitm.ac.in
        run: echo "Hello, world!"
